export const locationData = {
  Ayarwaddy: [
    "Bogale",
    "Danubyu",
    "Dedaye",
    "Einme",
    "Hinthada",
    "Ingapu",
    "Kangyidaunt",
    "Kyaiklat",
    "Kyangin",
    "Kyaunggon",
    "Kyonpyaw",
    "Labutta",
    "Laymyethna",
    "Maubin",
    "Mawlamyinegyun",
    "Myanaung",
    "Myaungmya",
    "Ngaputaw",
    "Nyaungdon",
    "Pantanaw",
    "Pathein",
    "Pyapon",
    "Thabaung",
    "Wakema",
    "Yegyi",
    "Zalun",
  ],
  Bago: [
    "Bago",
    "Daik-U",
    "Gyobingauk",
    "Kawa",
    "Kyaukkyi",
    "Kyauktaga",
    "Letpadan",
    "Minhla",
    "Monyo",
    "Nattalin",
    "Nyaunglebin",
    "Okpho",
    "Oktwin",
    "Padaung",
    "Paukkaung",
    "Paungde",
    "Pyay",
    "Pyu",
    "Shwedaung",
    "Shwegyin",
    "Tantabin",
    "Taungoo",
    "Thanatpin",
    "Thayarwaddy",
    "Thegon",
    "Waw",
    "Yedashe",
    "Zigon",
  ],
  Chin: [
    "Falam",
    "Hakha",
    "Kanpetlet",
    "Matupi",
    "Mindat",
    "Paletwa",
    "Tedim",
    "Thantlang",
    "Tonzang",
  ],
  Kachin: [
    "Bhamo",
    "Chipwi",
    "Hpakan",
    "Khaunglanhpu",
    "Machanbaw",
    "Mansi",
    "Mogaung",
    "Mohnyin",
    "Momauk",
    "Myitkyina",
    "N Jang Yang",
    "Nogmung",
    "Putao",
    "Shwegu",
    "Sumprabum",
    "Tanai",
    "Tsawlaw",
    "Waingmaw",
  ],
  Kayar: [
    "Bawlakhe",
    "Demoso",
    "Hpasawng",
    "Hpruso",
    "Loikaw",
    "Mese",
    "Shadaw",
  ],
  Kayin: [
    "Hlaingbwe",
    "Hpa-an",
    "Hpapun",
    "Kawkareik",
    "Kyain Seikgyi",
    "Myawaddy",
    "Thandaunggyi",
  ],
  Magway: [
    "Aunglan",
    "Chauk",
    "Gangaw",
    "Kamma",
    "Magway",
    "Minbu",
    "Mindon",
    "Minhla",
    "Myaing",
    "Myothit",
    "Natmauk",
    "Ngape",
    "Pakokku",
    "Pauk",
    "Pwintbyu",
    "Salin",
    "Saw",
    "Seikphyu",
    "Sidoktaya",
    "Sinbaungwe",
    "Taungdwingyi",
    "Thayet",
    "Tilin",
    "Yenangyaung",
    "Yesagyo",
  ],
  Mandalay: [
    "Amarapura",
    "Aungmyaythazan",
    "Chanayethazan",
    "Chanmyathasi",
    "Kyaukpadaung",
    "Kyaukse",
    "Madaya",
    "Maha Aungmye",
    "Mahlaing",
    "Meiktila",
    "Mogok",
    "Myingyan",
    "Myittha",
    "Natogyi",
    "Ngazum",
    "Nyaung-U",
    "Patheingyi",
    "Pyawbwe",
    "Pyigyidagun",
    "Pyin Oo Lwin",
    "Singu",
    "Sintgaing",
    "Tada-U",
    "Taungtha",
    "Thabeikkyin",
    "Thazi",
    "Wundwin",
    "Yamethin",
  ],
  Mon: [
    "Bilin",
    "Chaungzon",
    "Kyaikkhami",
    "Kyaikmaraw",
    "Kyaikto",
    "Mawlamyine",
    "Mudon",
    "Paung",
    "Thanbyuzayat",
    "Thaton",
    "Ye",
  ],
  Naypyitaw: [
    "Dekkhina Thiri",
    "Lewe",
    "Oattara Thiri",
    "Pobbathiri",
    "Pyinmana",
    "Tatkon",
    "Zabuthiri",
    "Zeyathiri",
  ],
  Rakhine: [
    "Ann",
    "Buthidaung",
    "Gwa",
    "Kyaukpyu",
    "Kyauktaw",
    "Maungdaw",
    "Minbya",
    "Mrauk-U",
    "Munaung",
    "Myebon",
    "Pauktaw",
    "Ponnagyun",
    "Ramree",
    "Rathedaung",
    "Sittwe",
    "Taungup",
    "Thandwe",
  ],
  Sagaing: [
    "Ayadaw",
    "Banmauk",
    "Budalin",
    "Chaung-U",
    "Hkamti",
    "Homalin",
    "Htigyaing",
    "Indaw",
    "Kale",
    "Kalewa",
    "Kanbalu",
    "Kani",
    "Katha",
    "Kawlin",
    "Khin-U",
    "Kyunhla",
    "Lahe",
    "Leshi",
    "Mawlaik",
    "Mingin",
    "Monywa",
    "Myaung",
    "Myinmu",
    "Nanyun",
    "Pale",
    "Paungbyin",
    "Pinlebu",
    "Sagaing",
    "Salingyi",
    "Shwebo",
    "Tabayin",
    "Tamu",
    "Tant-Se",
    "Wetlet",
    "Wuntho",
    "Ye-U",
    "Yinmabin",
  ],
  Shan: [
    "Hopang",
    "Hopong",
    "Hsenwi",
    "Hsihseng",
    "Hsipaw",
    "Kalaw",
    "Kengtung",
    "Konkyan",
    "Kunhing",
    "Kunlong",
    "Kutkai",
    "Kyaukme",
    "Kyethi",
    "Lai-Hka",
    "Langhko",
    "Lashio",
    "Laukkaing",
    "Lawksawk",
    "Loilem",
    "Mabein",
    "Mantong",
    "Matman",
    "Mawkmai",
    "Mong Hpayak",
    "Mong Hsat",
    "Mong Hsu",
    "Mong Khet",
    "Mong Kung",
    "Mong Nai",
    "Mong Pan",
    "Mong Ping",
    "Mong Ton",
    "Mong Yang",
    "Mong Yawng",
    "Mongla",
    "Mongmao",
    "Mongmit",
    "Mongyai",
    "Mu Se",
    "Namhkam",
    "Namhsan",
    "Namphan",
    "Namtu",
    "Nansang",
    "Nawnghkio",
    "Nyaungshwe",
    "Pangsang",
    "Pangwaun",
    "Pekon",
    "Pindaya",
    "Pinlaung",
    "Tachileik",
    "Tangyan",
    "Taunggyi",
    "Ywangan",
  ],
  Tanintharyi: [
    "Bokpyin",
    "Dawei",
    "Kawthaung",
    "Kyunsu",
    "Launglon",
    "Myeik",
    "Palaw",
    "Tanintharyi",
    "Thayetchaung",
    "Yebyu",
  ],
  Yangon: [
    "Ahlon",
    "Bahan",
    "Botataung",
    "Cocokyun",
    "Dagon",
    "Dagon Seikkan",
    "Dala",
    "Dawbon",
    "East Dagon",
    "Hlaing",
    "Hlaingthaya",
    "Hlegu",
    "Hmawbi",
    "Insein",
    "Kamayut",
    "Kawhmu",
    "Kayan",
    "Kungyangon",
    "Kyauktada",
    "Kyauktan",
    "Kyimyindaing",
    "Lanmadaw",
    "Latha",
    "Mayangon",
    "Mingala Taungnyunt",
    "Mingaladon",
    "North Dagon",
    "North Okkalapa",
    "Pabedan",
    "Pazundaung",
    "Sanchaung",
    "Seikkan",
    "Seikkyi Kanaungto",
    "Shwepyitha",
    "South Dagon",
    "South Okkalapa",
    "Taikkyi",
    "Tamwe",
    "Tantabin",
    "Thaketa",
    "Thanlyin",
    "Thingangyun",
    "Thongwa",
    "Twante",
    "Yankin",
  ],
};
